services:
  importreporter:
    build: .
    image: lpoaura/importgenerator:latest
    env_file:
      - .env
    volumes:
      - ${LOCAL_OUTPUT_DIR:-./output}:/home/user/output
      - ${LOCAL_LOG_DIR:-./logs}:/home/user/logs